server:
  port: 8001

spring:
  application:
    name: property
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/property?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root


swagger:
  enable: true

mybatis-plus:
  configuration:
    #map-underscore-to-camel-case: false #mybatis-plus关闭下划线驼峰命名，识别数据库索引 "_"
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml